# Generated by Django 5.1.7 on 2025-03-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0004_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                default="profile_pics/default.jpg", upload_to="profile_pics/"
            ),
        ),
    ]
